### ISSUE TITLE
How is this helpful?

### ISSUE THREAD

**Issue by optikalefx** [ronco/ember-cli-meta-tags#16]
The meta tags are added via JS. (obviously I guess). But Facebook share can't pick those up. So what is the point? Or am I missing a huge part of this?

**Comment by optikalefx** [comment]
It seems like I need to have nginx route 1 specific route to my API server. Which has to somehow server data into the HTML page for ember to pick up

**Comment by ronco** [comment]
Hey Sean,
Sorry for the confusion. Yes in order to get the benefit of this library
with a bot like Facebook you will need to pre-run the ember app server side
and deliver the resulting html.
There are services out there that will do this for you with phantomjs. I
personally use prerender.io. It has middleware adapters for several server
platforms including rails, node and nginx.
If you are using a node backend I will be updating this library to have
ember-cli-fastboot support when that has official head tag support. That
will give you the benefit of using this library entirely within the ember
add on ecosystem.
Also, thanks for the heads up on the install command deprecation. I'll get
that fixed up when I'm back in front of my computer.
Please feel free to hit me up on the ember slack room anytime.

**Comment by optikalefx** [comment]
Interesting, so with prerender, I suppose you use the nginx module? Since ember apps are served statically?

**Comment by ronco** [comment]
We actually use the expressJs middleware since we do have a very small
amount of server side logic for the initial page load written in node. I'm
sure the nginx module works great for purely static serving.
If your stack would support node (or another dynamic server) I recommend
you check out ember-cli-deploy combined with node-ember-cli-deploy-redis.
The combo makes for really smooth deployments and supports testing new
releases in production before you turn them on for the general user.

**Comment by optikalefx** [comment]
Yea we are a heavy ember-cli user, and I have an express based API server that the app connects to.  I have a really small deploy bash script that I use. It builds ember-cli for production, pulls the server, restarts and scp's all the files.  I see that cli-deploy uses s3 as a CDN, so there's that. But otherwise, i'm not sure the benefit over the bash script. (it's only 8 lines).  Why do you prefer it?

**Comment by ronco** [comment]
The main benefit of ember-cli-deploy is it takes care of updating your
index.html file with hash versioned css and js links and then it tracks
multiple copies of your index allowing you to test in production on a
different version than the one you've activated for users. Nice for sanity
checking before a bug hits production and makes for easy rollback if a
major bug slips through.

I know the system theoretically supports alternate stores for assets and
index.html, but we use redis and s3 which are the favored products.

All that being said "if it ain't broke don't fix it". If your script is
meeting your needs I wouldn't worry about it. I know ember-cli does a good
job of building out of the box.

**Comment by optikalefx** [comment]
s3 makes sense, but what are you using redis for? (we use it for sessions on the api server).
can't you just render the GIT hash into the index html to achieve the same sanity check?

**Comment by optikalefx** [comment]
I guess for the single html file? Does that really need to be in a store? (I can move this discussion to slack if you want)

**Comment by ronco** [comment]
With ember-cli-deploy-redis the index.html content for the last 10
deployments are actually stored in redis as well as a key pointing to which
one is currently active.

Rather than using the git revision for the files it uses a hash (sha1 I
think, but I may be mistaken) of the compiled asset file. The advantage
here is for long lived caching. If you do a deploy that only changes the
application js the vendor js files and the css file will not change the
file name and can remain cached in CDN and/or local browser caches. The
only time assets need to be redownloaded is if their content changes.

**Comment by ronco** [comment]
@optikalefx I'm going to close out this issue.  Feel free to open up a new one if you find any issues with this library, and hit me up @ronco on ember-slack.

**Comment by optikalefx** [comment]
Awesome, will do. Thanks
