### ISSUE TITLE
Adding Apple Smart App banner not showing up in iPhone

### ISSUE THREAD

**Issue by marlonmantilla** [ronco/ember-cli-meta-tags#18]
Hi guys currently experience this when  [Adding apple smart app banner meta tag](http://stackoverflow.com/questions/32100736/ember-cli-apple-smart-app-banner-not-working) ... 

I'm new to Ember and specially EmberCLI so any ideas will appreciate it.

**Comment by ronco** [comment]
Hey @marlonmantilla.

I'm not experienced with the apple smart app banner myself (I've used a home grown ember component as an app banner).  From another [stack overflow question](http://stackoverflow.com/questions/31289530/load-ios-smart-app-banner-through-javascript) it looks like Safari won't recognize the app banner tag if it's added asynchronously.

I'm working on getting this library to be [ember-cli-fastboot](https://github.com/tildeio/ember-cli-fastboot) compatible which would pre-execute your ember route server side and populate the initial head content for Safari.  (I hope to get it done next week on vacation).  However due to the [known limitations](https://github.com/tildeio/ember-cli-fastboot#known-limitations) of fastboot currently I don't know if that will be much help to you.

Looking at your SO question sample code it looks like you're just using the model id from the route params.  Could you parse the url server side and set up the meta tag on the initial html delivered to Safari?  That would get you the correct banner for direct page visits.  The big downside is it wouldn't dynamically update with the correct model id if the user navigates within your site.  I think this might be a core limitation of the smart app banner (and part of the reason we built our own).

**Comment by marlonmantilla** [comment]
Hi @ronco ` Could you parse the url server side and set up the meta tag on the initial html delivered to Safari? ` I was thinking on that possibility thanks for the suggestion, but I'm not sure how to add content to the initial html I assume the index.html file.  

On the server side rendering I'm using [Ember-prerender](https://github.com/zipfworks/ember-prerender) which solves my social network meta tags when crawling the site. But prerender as you can see is only for search engines and facebook crawler, not as an end user content.

**Comment by ronco** [comment]
Hey @marlonmantilla,

I wasn't familiar with `Ember-prerender`.  I actually use Todd Hooper's prerender service which they mention as an inspiration for Ember-prerender.  That service has the same limitation in that it only runs for bots, and strips out your javascript so the resulting page is completely static (no ember anymore).

Yeah, you would need to manipulate the index.html before sending it down the wire.  How you would do that depends on your server setup.

If you're just serving the file directly similar to the nginx config example Ember-prerender has you'll probably want to add in an application server frameworks such as [express.js](http://expressjs.com/) and then write a request handler that manipulates the html file.  We do something similar to embed per-request data into the initial page render.

I hope that helps.

**Comment by blimmer** [comment]
@ronco I think this can probably be closed?
