### ISSUE TITLE
issue with facebook

### ISSUE THREAD

**Issue by Soolan** [ronco/ember-cli-meta-tags#22]
Thank you for this wonderful add-on.
I can generate dynamic social tags and I can see them.
The problem that I have is that I can't see the proper preview when I share a link on facebook.
Any idea why it happens?

P.S
When I inspect the page in my browser (chrom, firefox, ...), I see the meta tags
but when I look at the page source, they are not there.
Could it be the reason? if yes how can I resolve this.
Thank you very much.

**Comment by ronco** [comment]
Hey @Soolan,

The problem is Facebook doesn't execute javascript with their bot.  So you just get the initial `index.html` with none of your ember application content.

The best solution for this (for now) is to use a service like [prerender.io](https://prerender.io/) or possibly an addon like [ember-prerender](https://github.com/zipfworks/ember-prerender).

Both of those require you to host your app within an app server (node.js for ember-prerender, or many different platforms for prerender.io).  

Eventually ember will provide prerendering with a core team addon called [ember-cli-fastboot](https://github.com/tildeio/ember-cli-fastboot).  That project's not quite ready for production use, but I will be working on that and this project to make sure we support setting head tags in fastboot when it is production ready.

Unfortunately all of these solutions require pre-executing the application on the server.  Dynamic ember app content just won't work with Facebook if you're serving your ember app from static hosting (such as github pages).

You can take a look at the discussion on #16 for more info, but I'm also happy to answer any further questions here.

Thanks!

-Ron

**Comment by Soolan** [comment]
Hello Ron,
That perfectly explains everything.
Thank you so much for your reply.
Kind Regards,
Sohail.

**Comment by Soolan** [comment]
Hello Ron,
That perfectly explains everything.
Thank you so much for your reply.
Kind Regards,
Sohail.
