### ISSUE TITLE
Why do all my generated meta tags have a "media=<foo>" attribute?

### ISSUE THREAD

**Issue by erichonkanen** [ronco/ember-cli-meta-tags#53]
All tags generated include a media attribute, what is causing that? it's leaking ember app structure...

`<meta property="og:image" content="https://foo.jpg" media="<client-web@service:media::ember227>" id="ember666" class="ember-view"></meta>`

**Comment by TimvdEijnden** [comment]
I've also got this issue

**Comment by ronco** [comment]
Are you using `ember-responsive`?  That library was auto-injecting itself into everything resulting in these tags being attached to tag nodes.  This was filed [here](https://github.com/freshbooks/ember-responsive/issues/77).  It looks like it's been fixed since then.  Alternatively it could be another addon with similar behavior, but the `media` attribute name makes me think it's `ember-responsive`.

**Comment by erichonkanen** [comment]
@ronco yes we're using that! going to take a look thanks...

**Comment by rizkysyazuli** [comment]
i was here looking for the same thing. turns out this is explained in their [README](https://github.com/freshbooks/ember-responsive#injection). on the section about **injection**.

It basically says to delete `app/initializers/responsive.js`.
