### ISSUE TITLE
FastBoot broken

### ISSUE THREAD

**Issue by simonihmig** [ronco/ember-cli-meta-tags#58]
As of the latest release, which includes the updated ember-cli-head 0.3.0 with FastBoot 1.0 support (#56), this addon does not render meta tags in FastBoot anymore. 

The root issue is this one: https://github.com/ember-fastboot/ember-cli-fastboot/issues/421

cc @cibernox

**Comment by simonihmig** [comment]
As a workaround for now, you can fix that by adding ember-cli-head as a direct dependency to you project, btw...

**Comment by cibernox** [comment]
@simonihmig I'm going to investigate it.

**Comment by simonihmig** [comment]
This has been identified as a bug in FastBoot itself (see the mentioned issue above), and fixed by https://github.com/ember-fastboot/ember-cli-fastboot/pull/423! 

Things should work again as expected with the next FastBoot release incorporating those changes. As there is nothing that remains to be done here, I will close this...

**Comment by Redsandro** [comment]
@simonihmig said:

> As a workaround for now, you can fix that by adding ember-cli-head as a direct dependency to you project

Should this also work with `ember-cli-fastboot` `beta.19`? Somehow I'm at a point where I can install all the beta versions, but starting with `rc.1`, the fastboot server will only return _bad request_.

Because if it should, I know I'm having a different problem, because the meta tags aren't showing up in the source. (They are _after_ fastboot, but that defeats the purpose.)

https://github.com/ember-fastboot/ember-cli-fastboot/issues/582
