### ISSUE TITLE
Deprecation warning: Implicit `router` injection

### ISSUE THREAD

**Issue by Turbo87** [ronco/ember-cli-meta-tags#96]
After updating https://github.com/rust-lang/crates.io to Ember 3.26 I've started seeing deprecation warnings that appear to be caused by this addon:

> DEPRECATION: A value was injected implicitly on the 'router' property of an instance of <cargo@service:head-tags::ember192>. Implicit injection is now deprecated, please add an explicit injection for this value. If the injected value is a service, consider using the @service decorator. [deprecation id: implicit-injections] See https://deprecations.emberjs.com/v3.x#toc_implicit-injections for more details.

**Comment by gzurbach** [comment]
Can anyone confirm this issue is a blocker for apps updating to Ember 4?

I'd assume the implicit injection is used to maintain backward compatibility with older version of Ember. I'd be happy to submit a pull request with guidance from the project maintainers. What versions of Ember is this library supposed to be compatible with? Could we consider doing the implicit injection only for apps running on older versions of Ember?

**Comment by snewcomer** [comment]
@gzurbach Yes, we need to refactor this - https://github.com/ronco/ember-cli-meta-tags/blob/8dae2dee0adb9ca517fb58630459d67d64a46937/addon/initializers/head-tags.js

I was hoping to get [this](https://github.com/ronco/ember-cli-meta-tags/pull/104) merged first.  Let me see if I can help get it across the line today.

**Comment by Turbo87** [comment]
FWIW I've refactored crates.io away from `ember-cli-meta-tags` in https://github.com/rust-lang/crates.io/pull/4064. Our usage of it was simple enough that we didn't need the additional addon.

**Comment by gzurbach** [comment]
@Turbo87 Thanks for the info. After digging into our code, we've reached the same conclusion: our needs are simple enough that `ember-cli-head` alone can do the job.

@snewcomer thank you for your work maintaining the library 🙏 And good luck for the upgrade 🌟

**Comment by bobisjan** [comment]
This can be closed #118 🥳
